-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables to ensure a clean start with correct columns
DROP TABLE IF EXISTS assessment_responses CASCADE;
DROP TABLE IF EXISTS assessments CASCADE;
DROP TABLE IF EXISTS peer_feedback CASCADE;
DROP TABLE IF EXISTS match_alerts CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS institutions CASCADE;
DROP TABLE IF EXISTS psychometric_items CASCADE;

-- 1. Create institutions table
CREATE TABLE institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT,
    domain TEXT UNIQUE NOT NULL,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create students table
CREATE TABLE students (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    graduation_year INTEGER NOT NULL,
    department TEXT NOT NULL,
    auth_id UUID UNIQUE,
    institution_id BIGINT REFERENCES institutions(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create assessments table
CREATE TABLE assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE NOT NULL,
    dimension_scores JSONB NOT NULL,
    founder_fit JSONB NOT NULL,
    primary_profile TEXT NOT NULL,
    development_report JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create psychometric_items table
CREATE TABLE psychometric_items (
    id TEXT PRIMARY KEY,
    stem TEXT NOT NULL,
    item_type TEXT NOT NULL,
    primary_dimension TEXT NOT NULL,
    secondary_dimensions TEXT[],
    tags TEXT[],
    intended_audience TEXT,
    options JSONB,
    scoring_logic JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create assessment_responses table
CREATE TABLE assessment_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE NOT NULL,
    assessment_id BIGINT REFERENCES assessments(id) ON DELETE CASCADE,
    question_id TEXT REFERENCES psychometric_items(id) ON DELETE CASCADE,
    response TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create market_leads table is already defined, let's make sure it has the fields
CREATE TABLE IF NOT EXISTS market_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    name TEXT,
    company TEXT,
    source TEXT,
    date_found DATE,
    ai_score INTEGER,
    ai_summary TEXT,
    ai_notes TEXT,
    status TEXT DEFAULT 'New',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_market_leads_url ON market_leads (url);
CREATE INDEX IF NOT EXISTS idx_market_leads_ai_score ON market_leads (ai_score);

-- 7. Create match_alerts table
CREATE TABLE match_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    lead_url TEXT NOT NULL REFERENCES market_leads(url) ON DELETE CASCADE,
    score INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_match_alerts_student_id ON match_alerts (student_id);

-- 8. Create peer_feedback table
CREATE TABLE peer_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID REFERENCES students(id) ON DELETE CASCADE NOT NULL,
    reviewer_email TEXT NOT NULL,
    reviewer_role TEXT,
    dimension_scores JSONB NOT NULL,
    feedback_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_peer_feedback_student_id ON peer_feedback (student_id);
