from __future__ import annotations

TECH_TAXONOMY: dict[str, tuple[str, ...]] = {
    "Python": ("python",),
    "TypeScript": ("typescript",),
    "JavaScript": ("javascript",),
    "C++": ("c++", "cpp"),
    "C#": ("c#", "c sharp"),
    "Java": ("java",),
    "PHP": ("php",),
    "Ruby": ("ruby",),
    "Go": ("golang", "go lang"),
    "Rust": ("rust",),
    "SQL": ("sql",),
    "React": ("react", "react.js", "reactjs"),
    "Next.js": ("next.js", "nextjs", "next js"),
    "Vite": ("vite",),
    "Tailwind": ("tailwind", "tailwindcss", "tailwind css"),
    "HTML": ("html",),
    "CSS": ("css",),
    "Vue": ("vue", "vue.js", "vuejs"),
    "Angular": ("angular",),
    "Svelte": ("svelte",),
    "Flutter": ("flutter",),
    "Swift": ("swift",),
    "Kotlin": ("kotlin",),
    "Android": ("android",),
    "iOS": ("ios", "i os"),
    "Node.js": ("node.js", "nodejs", "node js"),
    "Express": ("express", "express.js", "expressjs"),
    "NestJS": ("nestjs", "nest.js", "nest js"),
    "FastAPI": ("fastapi", "fast api"),
    "Django": ("django",),
    "Flask": ("flask",),
    "Laravel": ("laravel",),
    "Ruby on Rails": ("ruby on rails", "rails"),
    "WordPress": ("wordpress", "wp"),
    "REST API": ("rest api", "restful api", "restful", "rest endpoints", "api endpoint", "api endpoints"),
    "GraphQL": ("graphql", "graph ql"),
    "PostgreSQL": ("postgresql", "postgres", "neon postgres", "neon"),
    "MySQL": ("mysql",),
    "MongoDB": ("mongodb", "mongo"),
    "Redis": ("redis",),
    "Prisma": ("prisma",),
    "Drizzle": ("drizzle", "drizzle orm"),
    "Supabase": ("supabase",),
    "Qdrant": ("qdrant",),
    "Pinecone": ("pinecone",),
    "ChromaDB": ("chromadb", "chroma"),
    "Vector DB": ("vector database", "vector db", "vector store"),
    "RAG": ("rag", "retrieval augmented generation", "retrieval-augmented generation"),
    "LLM": ("llm", "large language model", "language model"),
    "AI Agents": ("ai agent", "ai agents", "agentic", "multi-agent", "multi agent"),
    "OpenAI": ("openai", "gpt", "chatgpt"),
    "Anthropic": ("anthropic", "claude"),
    "LangChain": ("langchain", "lang chain"),
    "LangGraph": ("langgraph", "lang graph"),
    "Machine Learning": ("machine learning", "ml engineer", "ml engineering", "ml ops", "mlops", "ml model", "ml pipeline", "ai/ml"),
    "NLP": ("nlp", "natural language processing"),
    "Computer Vision": ("computer vision", "vision model", "object detection", "image segmentation"),
    "PyTorch": ("pytorch", "torch"),
    "TensorFlow": ("tensorflow",),
    "Automation": ("automation", "workflow automation", "zapier", "n8n"),
    "Docker": ("docker", "container"),
    "Kubernetes": ("kubernetes", "k8s"),
    "Terraform": ("terraform",),
    "AWS": ("aws", "amazon web services"),
    "GCP": ("gcp", "google cloud"),
    "Azure": ("azure",),
    "Vercel": ("vercel",),
    "CI/CD": ("ci/cd", "cicd", "github actions"),
    "Linux": ("linux",),
    "WebSockets": ("websocket", "websockets", "socket.io"),
    "LiveKit": ("livekit", "livekit agents"),
    "Deepgram": ("deepgram",),
    "Groq": ("groq",),
    "Stripe": ("stripe",),
    "Firebase": ("firebase",),
    "Tauri": ("tauri",),
    "Electron": ("electron",),
    "Playwright": ("playwright",),
    "Data Pipeline": ("data pipeline", "etl", "data engineering"),
    "SAP": ("sap",),
    "ABAP": ("abap",),
    "Salesforce": ("salesforce", "apex"),
    "ServiceNow": ("servicenow", "service now"),
}


TECH_CATEGORY: dict[str, str] = {
    "Python": "language",
    "TypeScript": "language",
    "JavaScript": "language",
    "C++": "language",
    "C#": "language",
    "Java": "language",
    "PHP": "language",
    "Ruby": "language",
    "Go": "language",
    "Rust": "language",
    "SQL": "data",
    "React": "frontend",
    "Next.js": "frontend",
    "Vite": "frontend",
    "Tailwind": "frontend",
    "HTML": "frontend",
    "CSS": "frontend",
    "Vue": "frontend",
    "Angular": "frontend",
    "Svelte": "frontend",
    "Flutter": "mobile",
    "Swift": "mobile",
    "Kotlin": "mobile",
    "Android": "mobile",
    "iOS": "mobile",
    "Node.js": "backend",
    "Express": "backend",
    "NestJS": "backend",
    "FastAPI": "backend",
    "Django": "backend",
    "Flask": "backend",
    "Laravel": "backend",
    "Ruby on Rails": "backend",
    "WordPress": "cms",
    "REST API": "backend",
    "GraphQL": "backend",
    "PostgreSQL": "data",
    "MySQL": "data",
    "MongoDB": "data",
    "Redis": "data",
    "Prisma": "data",
    "Drizzle": "data",
    "Supabase": "data",
    "Qdrant": "ai",
    "Pinecone": "ai",
    "ChromaDB": "ai",
    "Vector DB": "ai",
    "RAG": "ai",
    "LLM": "ai",
    "AI Agents": "ai",
    "OpenAI": "ai",
    "Anthropic": "ai",
    "LangChain": "ai",
    "LangGraph": "ai",
    "Machine Learning": "ai",
    "NLP": "ai",
    "Computer Vision": "ai",
    "PyTorch": "ai",
    "TensorFlow": "ai",
    "Automation": "automation",
    "Docker": "infra",
    "Kubernetes": "infra",
    "Terraform": "infra",
    "AWS": "infra",
    "GCP": "infra",
    "Azure": "infra",
    "Vercel": "infra",
    "CI/CD": "infra",
    "Linux": "infra",
    "WebSockets": "backend",
    "LiveKit": "realtime",
    "Deepgram": "realtime",
    "Groq": "ai",
    "Stripe": "product",
    "Firebase": "backend",
    "Tauri": "desktop",
    "Electron": "desktop",
    "Playwright": "testing",
    "Data Pipeline": "data",
    "SAP": "enterprise",
    "ABAP": "enterprise",
    "Salesforce": "enterprise",
    "ServiceNow": "enterprise",
}


ROLE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "ai": (
        "ai engineer", "ai developer", "ai/ml engineer", "ai/ml developer",
        "applied ai", "applied ml", "ml engineer", "machine learning engineer",
        "llm engineer", "llm developer", "ai agent", "agentic", "rag engineer",
        "prompt engineer", "genai", "generative ai", "ai automation",
        "chatbot developer", "chatbot engineer",
    ),
    "backend": (
        "backend", "back-end", "back end", "server engineer", "microservice",
        "platform engineer", "python developer", "node developer",
        "api engineer", "api developer",
    ),
    "frontend": (
        "frontend", "front-end", "front end", "react developer", "react engineer",
        "next.js developer", "web developer", "ui engineer", "ui developer",
    ),
    "fullstack": (
        "full stack", "full-stack", "software engineer", "product engineer",
        "web app developer", "saas engineer", "application developer",
    ),
    "data": ("data engineer", "analytics engineer", "etl engineer", "data pipeline"),
    "devops": ("devops", "cloud engineer", "sre", "site reliability", "infrastructure engineer", "platform reliability"),
    "mobile": ("mobile developer", "ios developer", "android developer", "react native", "flutter developer"),
    "desktop": ("desktop app", "electron developer", "tauri developer"),
    "testing": ("qa automation", "test automation", "playwright engineer"),
}


DELIVERABLE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "ai agent": ("ai agent", "agentic", "multi-agent", "workflow agent"),
    "rag": ("rag", "retrieval", "knowledge base", "semantic search"),
    "chatbot": ("chatbot", "chat bot", "assistant", "copilot"),
    "voice ai": ("voice ai", "voice agent", "speech", "deepgram", "livekit"),
    "automation": ("automation", "workflow", "scraper", "bot"),
    "dashboard": ("dashboard", "admin panel", "analytics"),
    "saas": ("saas", "multi-tenant", "subscription"),
    "api": ("rest api", "graphql api", "backend api", "server api"),
    "frontend app": ("frontend", "ui", "landing page", "web app"),
    "full-stack app": ("full stack", "full-stack", "end-to-end", "web app"),
    "data pipeline": ("data pipeline", "etl", "ingestion"),
    "fintech": ("fintech", "finance", "payments", "stripe"),
    "desktop app": ("desktop app", "tauri", "electron"),
    "testing": ("test automation", "qa automation", "playwright"),
}


WRONG_FIELD_TERMS = (
    "nurse", "doctor", "physician", "medical assistant", "pharmacist",
    "accountant", "bookkeeper", "tax preparer", "lawyer", "paralegal",
    "cashier", "retail associate", "warehouse", "driver", "delivery",
    "cook", "chef", "mechanic", "civil engineer", "mechanical engineer",
    "electrical engineer", "chemical engineer", "petroleum engineer",
    "embedded systems engineer", "rtos", "arm cortex", "can bus", "autosar",
    "real estate agent", "insurance agent", "teacher", "tutor", "data entry",
    "marketing analyst", "marketing manager", "marketing specialist",
    "marketing coordinator", "social media manager", "content writer",
    "copywriter", "blog writer", "seo specialist", "seo writer",
    "sales representative", "sales manager", "sales executive", "sdr",
    "account executive", "account manager", "customer success",
    "customer service", "customer support agent", "call center",
    "recruiter", "talent acquisition", "human resources", "hr manager",
    "executive assistant", "virtual assistant", "personal assistant",
    "graphic designer", "video editor", "animator", "illustrator",
    "translator", "transcriber", "voice actor", "video producer",
    "construction", "plumber", "electrician", "welder", "carpenter",
    "barista", "waiter", "waitress", "bartender",
    "security guard", "janitor", "housekeeper", "babysitter",
)


RED_FLAGS = (
    "unpaid", "for exposure", "equity only", "college assignment", "homework",
    "no budget", "cheap", "lowest bidder", "free trial", "commission only",
    "crypto token", "urgent cheap", "do not apply", "training course",
)


COMMERCIAL_TERMS = (
    "hiring", "job opening", "open role", "role available", "apply",
    "we're hiring", "we are hiring", "is hiring", "internship",
    "junior", "entry level", "new grad", "graduate",
)


_MONTHS = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
    "jul": 7, "aug": 8, "sep": 9, "sept": 9, "oct": 10, "nov": 11, "dec": 12,
}
