import os
import sys
import json

# Add the backend to path so we can import the scoring engine
sys.path.append(os.path.join(os.getcwd(), "services", "job-intel-desk", "backend"))

try:
    from agents.scoring_engine import score_job_lead, analyze_candidate, analyze_posting
except ImportError as e:
    print(f"Error importing scoring engine: {e}")
    print("Ensure you are running this from the project root.")
    sys.exit(1)

def generate_ordeal_prompt(candidate_data, job_description):
    """
    Unit 2: Automates the handoff from Audit to Ordeal.
    Transforms audit findings (gaps) into targeted interview scripts for the agents.
    """
    # 1. Run the Audit (Scoring Engine)
    result = score_job_lead(job_description, candidate_data)
    candidate_ev = analyze_candidate(candidate_data)
    posting_ev = analyze_posting(job_description)
    
    # 2. Extract Key Gaps and Missing Stack
    gaps = result.gaps
    missing_stack = posting_ev.terms - candidate_ev.all_terms
    
    # 3. Generate Targeted Prompts for the Agent Swarm
    prompt = f"""
# ORDEAL MISSION: STRESS-TEST SESSION
## Target Role: {posting_ev.title} at {posting_ev.company if posting_ev.company else 'Confidential'}
## Candidate: {candidate_data.get('candidate', {}).get('name', 'The Candidate')}

### 🚨 IDENTIFIED AUDIT GAPS (THE TARGETS)
{chr(10).join([f"- {gap}" for gap in gaps])}

### 🛠️ MISSING TECHNICAL STACK
{', '.join(missing_stack) if missing_stack else 'None identified.'}

### 📋 INSTRUCTIONS FOR THE AGENTS:
You are to conduct a high-pressure "Ordeal" session. Do not play nice. 
Target the specific gaps identified above.

- **Anthropologist:** Question if the candidate's previous "tribal" experiences (past companies) have prepared them for the cultural rigors of {posting_ev.company if posting_ev.company else 'this specific firm'}.
- **Engineering Agent:** Drill deep into the 'Missing Technical Stack' listed above. If they claim knowledge not in the audit, demand architectural proof.
- **Psychologist:** Pressure-test the candidate's 'Seniority Fit'. If the audit says they are 'Junior' for a 'Senior' role, find where they will break under responsibility.
- **Narratologist:** Challenge the coherence of their career story. If there are gaps in their timeline or stack, treat them as "unreliable narrators."

---
*This prompt was automatically generated by the campus2corporate (c2c) Orchestrator.*
"""
    return prompt

if __name__ == "__main__":
    # Sample Data for Demonstration
    sample_candidate = {
        "candidate": {"name": "Jane Doe", "summary": "Frontend Specialist"},
        "skills": [{"n": "React"}, {"n": "TypeScript"}],
        "projects": [{"title": "Web Dashboard", "stack": "React, Vite", "impact": "High-perf UI"}],
        "exp": [{"role": "Junior Developer", "co": "StartupX", "period": "2023-2024", "d": "Built UIs"}]
    }
    
    sample_jd = """
    Job Title: Senior Full-Stack Engineer
    Company: TechGiant
    Description: We need a veteran who can lead our cloud migration. 
    Required Stack: Python, FastAPI, AWS, Terraform, React.
    Years of Experience: 5+ years.
    """
    
    print("--- GENERATING ORDEAL PROMPT ---")
    ordeal_prompt = generate_ordeal_prompt(sample_candidate, sample_jd)
    print(ordeal_prompt)
    
    # Save to file for Unit 2 confirmation
    with open("ORDEAL_PROMPT_PROTOTYPE.md", "w", encoding="utf-8") as f:
        f.write(ordeal_prompt)
    print("\n✅ Prototype saved to ORDEAL_PROMPT_PROTOTYPE.md")
